-- Version 1.1
if branch == "development" then
    status = run("npm", "--no-color install")
    setStatus(status)
    status = run("rm", "-rfv ./build/")
    setStatus(status)
    status = run("npm", "--no-color run build")
    setStatus(status)
    status = run("npm", "--no-color run knex:migrate")
    setStatus(status)
    status = run("npm", "--no-color run knex:seed")
    setStatus(status)
    status = run("rm", "-rfv /home/rgd/deploy/dev/backend/")
    setStatus(status)
    status = run("cp", "-rv ./build/ /home/rgd/deploy/dev/backend/")
    setStatus(status)
elseif branch == "master" then
    status = run("npm", "--no-color install")
    setStatus(status)
    status = run("rm", "-rfv ./build/")
    setStatus(status)
    status = run("npm", "--no-color run build")
    setStatus(status)
    status = run("npm", "--no-color run knex:migrate")
    setStatus(status)
    status = run("npm", "--no-color run knex:seed")
    setStatus(status)
    status = run("rm", "-rfv /home/rgd/deploy/dist/backend/")
    setStatus(status)
    status = run("cp", "-rv ./build/ /home/rgd/deploy/dist/backend/")
    setStatus(status)
end
